# Generated by Django 2.0.2 on 2018-02-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='name',
            field=models.CharField(default=16, max_length=10),
        ),
        migrations.AddField(
            model_name='college',
            name='types',
            field=models.CharField(default=16, max_length=10),
        ),
    ]
