# Generated by Django 2.0.2 on 2018-02-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20180225_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='name',
        ),
        migrations.RemoveField(
            model_name='college',
            name='types',
        ),
    ]
